# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-Comma
version:      1.24
version_from: lib/XML/Comma.pm
installdirs:  site
requires:
    Class::ClassDecorator:         0
    Compress::Zlib:                0
    Crypt::CBC:                    0
    Crypt::Twofish:                0
    DBI:                           0
    Digest::HMAC_MD5:              0
    Inline:                        0
    Lingua::Stem:                  0
    Math::BaseCalc:                0
    String::CRC:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
